services:
  development:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
      - "35729:35729"
    volumes:
      - .:/app
    container_name: development
    image: order:v1.0
    environment:
      - DJANGO_DEVELOPMENT=True

  production:
    build: .
    ports:
      - "9000:80"
    volumes:
      - .:/app
      - ./config/nginx:/etc/nginx/conf.d
      - ./config/supervisor:/etc/supervisor/conf.d

    container_name: production
    image: hosamhamdy/orders-manager:v1.0
    environment:
      - DJANGO_DEVELOPMENT=False
