services:
  order-back-end:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
      - "35729:35729"
    volumes:
      - .:/app
    container_name: order
    image: order:v1.0
